# Generated by Django 5.1.1 on 2025-01-25 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.curso'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vinculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vinculo'),
        ),
    ]
