# Generated by Django 5.1.1 on 2025-01-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/imgs/ari.jpg', null=True, upload_to='avatars/'),
        ),
    ]
