# Generated by Django 5.1.1 on 2025-02-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_primeiro_nome_profile_ultimo_sobrenome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculo',
            name='vinculo',
            field=models.CharField(max_length=50),
        ),
    ]
