# Generated by Django 5.1.1 on 2024-10-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('justificativa', models.TextField(max_length=120)),
                ('resumo', models.TextField(max_length=255)),
                ('data_publi', models.DateField(auto_now=True)),
                ('usuarios', models.ManyToManyField(to='ppi.usuario')),
            ],
        ),
    ]
