# Generated by Django 5.1.1 on 2024-12-01 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('descricao', models.TextField(max_length=120)),
                ('resumo', models.TextField(max_length=2000)),
                ('capa', models.ImageField(upload_to='')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppi.curso')),
                ('usuarios1', models.ManyToManyField(to='ppi.usuario1')),
                ('usuarios2', models.ManyToManyField(to='ppi.usuario2')),
            ],
        ),
        migrations.CreateModel(
            name='FotoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ppi.projeto')),
            ],
        ),
    ]
