# Generated by Django 5.1.1 on 2024-12-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='logo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
