# Generated by Django 5.1.1 on 2025-01-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0002_alter_curso_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='descricao',
        ),
        migrations.AddField(
            model_name='projeto',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projeto',
            name='objetivo',
            field=models.TextField(default='Obetivo padrão, padrão objetivo. Este campo não pode ser nulo.', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='palavrasChave',
            field=models.CharField(default='projeto integrador', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='curso',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='resumo',
            field=models.TextField(max_length=120),
        ),
    ]
