# Generated by Django 5.1.1 on 2024-10-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0002_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
