# Generated by Django 5.1.1 on 2025-01-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0003_remove_projeto_descricao_projeto_images_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario1',
            new_name='Aluno',
        ),
        migrations.RenameModel(
            old_name='Usuario2',
            new_name='Orientador',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='usuarios1',
            new_name='alunos',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='usuarios2',
            new_name='orientadores',
        ),
    ]
