# Generated by Django 5.1.1 on 2024-10-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0003_alter_usuario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, upload_to='media/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuario1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='post',
            name='usuarios1',
            field=models.ManyToManyField(to='ppi.usuario1'),
        ),
        migrations.AddField(
            model_name='post',
            name='usuarios2',
            field=models.ManyToManyField(to='ppi.usuario2'),
        ),
    ]
