# Generated by Django 5.1.1 on 2024-11-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0004_usuario2_rename_usuario_usuario1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resumo',
            field=models.TextField(max_length=2000),
        ),
    ]
