# Generated by Django 5.1.1 on 2024-11-30 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0005_alter_post_resumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('descricao', models.TextField(max_length=120)),
                ('resumo', models.TextField(max_length=2000)),
                ('capa', models.ImageField(upload_to='')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppi.curso')),
            ],
        ),
    ]
