# Generated by Django 5.1.1 on 2025-01-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0005_rename_palavraschave_projeto_palavras_chave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='capa',
            field=models.ImageField(upload_to='', verbose_name='media/'),
        ),
    ]
