# Generated by Django 5.1.1 on 2024-12-01 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0006_curso_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='usuarios1',
            field=models.ManyToManyField(to='ppi.usuario1'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='usuarios2',
            field=models.ManyToManyField(to='ppi.usuario2'),
        ),
        migrations.CreateModel(
            name='FotoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ppi.projeto')),
            ],
        ),
    ]
