# Generated by Django 5.1.1 on 2024-12-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0007_projeto_usuarios1_projeto_usuarios2_fotoprojeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
