# Generated by Django 5.1.1 on 2025-01-06 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0007_rename_images_projeto_imagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppi.curso'),
        ),
    ]
