# Generated by Django 5.1.1 on 2025-01-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0008_alter_projeto_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='curso',
            field=models.CharField(max_length=80),
        ),
    ]
