# Generated by Django 5.1.1 on 2024-12-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0008_alter_curso_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='nome',
            new_name='titulo',
        ),
    ]
