# Generated by Django 5.1.1 on 2025-01-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0009_alter_projeto_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='palavras_chave',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='resumo',
            field=models.TextField(max_length=1000),
        ),
    ]
