# Generated by Django 5.1.1 on 2025-01-10 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0012_rename_comentario_comentario_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='ppi.projeto'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
