# Generated by Django 5.1.1 on 2025-01-13 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0013_comentario_projeto_projeto_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppi.curso'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='resumo',
            field=models.TextField(max_length=150),
        ),
    ]
