# Generated by Django 5.1.1 on 2025-01-13 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0014_alter_projeto_curso_alter_projeto_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='ppi.curso'),
        ),
    ]
