# Generated by Django 5.1.1 on 2025-01-25 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0016_alter_projeto_curso'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='users.curso'),
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
