# Generated by Django 5.1.1 on 2025-01-25 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0017_alter_projeto_curso_delete_curso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='componentes',
            field=models.ManyToManyField(blank=True, related_name='projetos', to=settings.AUTH_USER_MODEL),
        ),
    ]
