# Generated by Django 5.1.1 on 2025-01-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0018_projeto_componentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='projetos', to='ppi.aluno'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='orientadores',
            field=models.ManyToManyField(blank=True, related_name='projetos', to='ppi.orientador'),
        ),
    ]
