# Generated by Django 5.1.1 on 2025-01-28 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0019_alter_projeto_alunos_alter_projeto_orientadores'),
        ('users', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='alunos',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='orientadores',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='componentes',
            field=models.ManyToManyField(blank=True, related_name='projetos', to='users.profile'),
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Orientador',
        ),
    ]
