# Generated by Django 5.1.1 on 2025-02-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0020_remove_projeto_alunos_remove_projeto_orientadores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='imagens',
        ),
    ]
