# Generated by Django 5.1.1 on 2025-02-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0021_remove_projeto_imagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='resumo',
            field=models.TextField(max_length=2000),
        ),
    ]
