# Generated by Django 5.1.1 on 2025-02-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0022_alter_projeto_resumo'),
        ('users', '0009_alter_vinculo_vinculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='componentes',
        ),
        migrations.AddField(
            model_name='projeto',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='projetos_aluno', to='users.profile'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='professores',
            field=models.ManyToManyField(blank=True, related_name='projetos_professor', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='objetivo',
            field=models.TextField(max_length=4000),
        ),
    ]
