# Generated by Django 5.1.1 on 2025-02-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppi', '0023_remove_projeto_componentes_projeto_alunos_and_more'),
        ('users', '0009_alter_vinculo_vinculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='alunos',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='professores',
        ),
        migrations.AddField(
            model_name='projeto',
            name='orientadores',
            field=models.ManyToManyField(blank=True, related_name='projetos_orientadores', to='users.profile'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='orientados',
            field=models.ManyToManyField(blank=True, related_name='projetos_orientados', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='objetivo',
            field=models.TextField(max_length=2000),
        ),
    ]
